name: train_macco_clip_coco
train_data: mscoco_object_relation_attribute_with_phrase_bbox.tsv
logs: ./logs/train_MACCO_CLIP/ViT-B-32
pretrained: openai
model: ViT-B-32
seed: 0
batch_size: 256 # 128 for ViT-B-16, 48 for ViT-L-14 due to GPU memory limit
gradient_accumulation_steps: 1
epochs: 5
two_stage: False
first_stage_epochs: 0
second_stage_epochs: 5
mask_text_image: True
mask_image: False
mask_text: False
random_rectangular_mask_prob: 0.1
mask_region_reserve_ratio: 1.0
random_mask_image: False
random_mask_image_ratio: 0.75
random_rectangular_mask_image: False
random_rectangular_mask_image_ratio: 0.75
random_mask_text: False
random_mask_text_ratio: 0.15
rebuild_dataset_every_epoch: False
wd: 0.2
workers: 14
warmup: 50
save_frequency: 5
lr_clip: 5.0e-7
lr_predictor: 1.0e-3
report_to: tensorboard
only_train_clip: False
macco_clip_version: text_image
loss_fn: loss_text_image
text_predictor_self_attn_layers: 0
text_predictor_cross_attn_layers: 2 # 4 for ViT-B-16 and ViT-L-14
image_predictor_self_attn_layers: 0
image_predictor_cross_attn_layers: 3 # 6 for ViT-B-16 and ViT-L-14
mask_token_type: relation_and_attribute
freeze_clip: False
freeze_image_encoder: False
freeze_text_encoder: False
distributed: False
val_before_train: False
seperate_relation_attribute: False
add_neg_sample: False
contrast_loss_w: 1.0
intra_modal_contrast_loss_w: 0.1
mask_text_loss_w: 20.0
mask_image_loss_w: 250.0
EMA: False